storeId: ""
storeName: ""
namespace: ""

mysql:
  image: mysql:8.0
  database: wordpress
  user: wpuser
  password: ""
  rootPassword: ""
  storage: 5Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

wordpress:
  image: wordpress:6.4-apache
  storage: 10Gi
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "500m"

ingress:
  enabled: true
  className: nginx
  clusterIP: "127.0.0.1"

resourceQuota:
  enabled: true
  maxCPU: "2"
  maxMemory: "4Gi"
  maxStorage: "20Gi"
  maxPVCs: "5"

limitRange:
  enabled: true
  defaultRequestCPU: "100m"
  defaultRequestMemory: "256Mi"
  defaultLimitCPU: "500m"
  defaultLimitMemory: "512Mi"
