apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    store-id: {{ .Values.storeId }}
    managed-by: store-platform
  annotations:
    store-name: {{ .Values.storeName | quote }}
