apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  root-password: {{ .Values.mysql.rootPassword | b64enc }}
  password: {{ .Values.mysql.password | b64enc }}
  database: {{ .Values.mysql.database | b64enc }}
  username: {{ .Values.mysql.user | b64enc }}
