apiVersion: v1
kind: Service
metadata:
  name: woocommerce-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: woocommerce
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
